### PR TITLE
Replacing crime data for the public safety tabs

### LINKED ISSUE #445: + fbi crime data nationwide
take 1:

* multiyear
* cities only

### PR DESCRIPTION
**Pull request by chrismetcalf**
Will close #445.

- [x] Remove geographic limits
- [x] Wire in FBI UCR datasets
- [x] Replace boilerplate with FBI UCR content
   - Include link to UCR data
- [x] Add an "all crimes" rate and count to the dataset, make that the default
- [x] Kill the "For the selected regions..." intersect and text
- [ ] Fix tests
- [ ] Update comparisons
- [x] Get CR from @aaasen 

Staged at: http://odn-fbi-ucr.herokuapp.com/region/1600000US5300100/Aberdeen_WA/city_crime/murder_and_nonnegligent_manslaughter_rate/2014

### CODE REVIEW

**Comment by zang0** [comment]
Looks like the maps are having issues. See: http://odn-fbi-ucr.herokuapp.com/region/1600000US5363000/Seattle_WA/city_crime/larceny_-theft_rate/2014?

but if you look at the data source: 

https://odn.data.socrata.com/dataset/Nationwide-City-Level-FBI-UCR-Data-2006-2014/8x3g-rxtx

you can see the 2014 seattle larceny theft data is indeed there.

**Comment by chrismetcalf** [comment]
@zang0 Yeah that's one of the things that I wanted to talk to @aaasen about. The framework generates a query that pulls 5000 cities, which it then pulls out it's chosen city from for the map:

https://github.com/socrata/opendatanetwork.com/pull/453/commits/33fe4af3dd60c40ca092269f3803880330dd67c1#diff-418a3021138863a774e2491cb86ba8daL678

I changed the query from `ASC` to `DESC`, which gets it to work for "higher crime" cities, but I'm not sure why it's doing that. I can change the query to just pull the one city, but I think it might break the map for comparisons.

@aaasen Lil help here?

**Comment by chrismetcalf** [comment]
There's also an issue where the FBI uses three different hyphenations for "Larceny" as well. Might be related. Rerunning with a fix for that too.

**Comment by chrismetcalf** [comment]
Looks like it was the differing hyphenations problem, Larceny looks better for Seattle now: http://odn-fbi-ucr.herokuapp.com/region/1600000US5363000/Seattle_WA/city_crime/larceny_rate/2014

Map still isn't showing up, but that's a CORS error from MapBox, should be fixed once we're on staging.

**Comment by aaasen** [comment]
Is there anything else? The map is showing up for me.

**Comment by zang0** [comment]
Some more comments:

_1 Having crime totals w/ total rates as the default landing in the maps would be nice

_2 Need to change the source citation to point to the FBI - currently sites CrimeReports.com - see: "Above charts are based on data from the CrimeReports.com ..." @ http://odn-fbi-ucr.herokuapp.com/region/1600000US1714000-1600000US1827000/Chicago_IL-Gary_IN/city_crime/aggravated_assault_rate/2012?

_3 Trying to verify some of the year holes in the source data, like 2010 missing crime for Gary INdiana but not sure exactly where the source files are. Do we know what the cause of these holes are?

_4 Is this passage still relevant: "For the selected regions, the following crime types are available: Murder and nonnegligent manslaughter, Arson, Robbery, Aggravated assault, Motor vehicle theft, Burglary, Larceny, Property crime." I thought the FBI data is consistent across all the crimes shown in the drop down - looks off. (Clip For URL above)

_5 Looks like COMPARE THIS DATA autosuggest is not working - still constrained to Maryland per our original impl

_6 Have we vetted the crime rates numbers for cities, some combos come back confusing, like i'd expect seattle to have a lower per capita crime rate than chicago, but it doesn't.

**Comment by chrismetcalf** [comment]
FYI, this is all merged now, but I missed my window to get it in before @ToshMeston integrated the availability API calls.

Working with @aaasen to get crime data added to the ODN API. There's a bug in the variables generation script right now, and he's going to fix that.

**Comment by aaasen** [comment]
Fixed the script and improved docs. See https://github.com/socrata/odn-backend/tree/master/data#update-variables

**Pull request merged**
